### ISSUE TITLE
Release date for models and code

### ISSUE THREAD

**Issue by minh-nnm** [bcmi/DCI-VTON-Virtual-Try-On#1]
Hi,

Once again, great paper. When do you plan to release the other things such as the inference script, pretrained model, and training scripts.

**Comment by Limbor** [comment]
Hi, @minh-nnm, thanks for your attention! We plan to release the pretrained model and inference code around September 1, and release all resources in September.

**Comment by kongds1998** [comment]
Hi，
I am interested in your job. Do you have any plans to release the training code in the future?

**Comment by Limbor** [comment]
We have released the code and model weights for inference.

**Comment by RishiGitH** [comment]
@Limbor Thanks a lot for that, excited to test it out. How do I test it on my own Human image and cloth image . Would i need a pipeline to create the parsings like VITON and by any chance do you have one

**Comment by Limbor** [comment]
@RishiGitH For image preprocessing, you can refer to HR-VTON’s [preprocessing](https://github.com/sangyun884/HR-VITON/blob/main/Preprocessing.md) doc.

**Comment by sriramun** [comment]
Thank you for your contributions! 
Are you planning to release the pretrained models trained on the Deepfashion dataset?
