### ISSUE TITLE
Where can I get VITON-HD 512?

### ISSUE THREAD

**Issue by kasim0226** [bcmi/DCI-VTON-Virtual-Try-On#12]
Thank you for your great work.

I followed the tutorial and download the VITON-HD dataset from the link you provided (https://github.com/shadow2496/VITON-HD), however the dataset image size is 1024*768.
Your pretrained model is 512, could I know there to get the 512 dataset?

**Comment by sachintha443** [comment]
@kasim0226 how you solve this
