### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Drewsipherr** [bcmi/DCI-VTON-Virtual-Try-On#14]
Hi, any opinions on using ```https://github.com/sergeywong/cp-vton``` instead of VITON-HD? Saw in a similar project that they chose cp instead of HD due to copywrite issues.

**Comment by Limbor** [comment]
Hi @Drewsipherr As far as I know, the main difference between the VITON dataset used by cp-vton and VITON-HD is the image resolution. Except for the difference in resolution, you only need to consider using the data it provides to train the warping module, and the diffusion model part does not require too many modifications.
