### ISSUE TITLE
Custom Image

### ISSUE THREAD

**Issue by Deepak2405** [bcmi/DCI-VTON-Virtual-Try-On#16]
Hi, thank you for the code. Could you let us know how to test for a custom image. What are the requirements and what changes we need to make in the code?

**Comment by Limbor** [comment]
Hi, you should fisrt do some preprocessing on the custom data referring to https://github.com/sangyun884/HR-VITON/issues/45#issue-1515217009. After this, you can refer to the dataset and inference related codes of the warping module and diffusion model in our code to process these data.
