### ISSUE TITLE
Where is the base.py?

### ISSUE THREAD

**Issue by zmj1203** [bcmi/DCI-VTON-Virtual-Try-On#17]
When I run train.sh or main.py to trian a diffusion model, it has an error:
File "main.py", line 21, in <module>
    from ldm.data.base import Txt2ImgIterableBaseDataset
ModuleNotFoundError: No module named 'ldm.data.base'

I found that there is not a base.py file in the path of ./ldm/data/, maybe you forget to upload this file? Can I use the files in the paint-by-examples project directly? Did you modify this file in the paint-by-example?

**Comment by Limbor** [comment]
Hi, just delete it, we will fix it soon. Thank you for your reminder!
