### ISSUE TITLE
get cloth-warp image use my dataset

### ISSUE THREAD

**Issue by chunxia75qin** [bcmi/DCI-VTON-Virtual-Try-On#23]
when I use the warp model provided by author to get cloth-warp image, I find it less effective. so I need to use my dataset to train a warp model, use train_VITON.sh, but how to get cloth-warp image for training, are cloth-warp gt image manually annotated？

**Comment by Limbor** [comment]
The reason may be the same as https://github.com/bcmi/DCI-VTON-Virtual-Try-On/issues/19#issuecomment-1751629201. And for training, you need do the preprocessing on your data and organize these data like the VITON-HD dataset, then training.
