### ISSUE TITLE
How to train 1024 resolution diffusion model?

### ISSUE THREAD

**Issue by bigcornflake** [bcmi/DCI-VTON-Virtual-Try-On#24]
> We utilize the pretrained Paint-by-Example as initialization, please download the pretrained models from Google 

But Paint-by-Example does not have a 1024 resolution model. 
which model I can utilize as initialization to train 1024 resolution diffusion model?
Thanks

**Comment by Limbor** [comment]
Hi @bigcornflake you can still use the pretrained weight of Paint by Example as 512 resolution as initialization.

**Comment by bigcornflake** [comment]
Thanks，I'll try it
