### ISSUE TITLE
Could you describe how to use cp_dataset_v2.py and what is the selection strategy update?

### ISSUE THREAD

**Issue by YSL0226** [bcmi/DCI-VTON-Virtual-Try-On#38]
Hi authors,

Could you describe how to use cp_dataset_v2.py and what is the selection strategy update?

Looking forward to your reply

**Comment by Limbor** [comment]
Hi, just change the configuration files in the training and inference scripts to viton512_v2.yaml, and the ckeckpoint location used during inference also needs to be reset to the new weight file location. This update mainly uses the mask selection strategy of HR-VTON, Intuitively, the mask area is larger. Compared with the previous version, this strategy will make the generated results less likely to be affected by the shape of the person's original clothes.

**Comment by YSL0226** [comment]
Thank you for the answer
