### ISSUE TITLE
HELP! EOFError: Ran out of input

### ISSUE THREAD

**Issue by xuepeilei** [bcmi/DCI-VTON-Virtual-Try-On#42]
I am sure that I have deployed it according to the author's requirements and put the viton512.ckpt file in the checkpoint folder. This file is not empty. Can u help me to solve this promblem?
![Uploading 微信截图_20240127235545.p
![微信截图_20240127235618](https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/16931942/c64fc28a-e5fc-4bcd-b13c-796e1de21bc4)
ng…]()

**Comment by xuepeilei** [comment]
![微信截图_20240127235618](https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/16931942/d3aad5d6-1f72-4a0e-b03a-4509576d2bf1)
![微信截图_20240127235545](https://github.com/bcmi/DCI-VTON-Virtual-Try-On/assets/16931942/101cb788-b716-4259-85af-ab505dd3d4a7)

**Comment by sachintha443** [comment]
@xuepeilei how you resolve this
