### ISSUE TITLE
warp model

### ISSUE THREAD

**Issue by hamaadtahiir** [bcmi/DCI-VTON-Virtual-Try-On#7]
Will you release the warp model as well? Also does your experiment include results for 1024x768 resolution?

**Comment by Limbor** [comment]
Yes, we will update the warping model soon. About other resolution model, we do not plan to release. You can train it by modifying the model config. Thank you for your interest in our work.

**Comment by garychan22** [comment]
@Limbor Hi, should we load the warp model using [https://github.com/geyuying/PF-AFN/tree/main](url) since the params' dimensions mismatch the default network setting in PF-AFN

**Comment by Limbor** [comment]
Hi @garychan22 We have released the inference and training code for warping module

**Comment by FYtrace** [comment]
do we need pose, densepose, cloth_mask, and others? It seems cp_datasets.py read these message. [https://github.com/bcmi/DCI-VTON-Virtual-Try-On/blob/872b823f1daec9a187dc7a943434bf9520245070/warp/test/data/cp_dataset.py#L202C27-L202C27](url)

**Comment by Limbor** [comment]
Yes, the VITON-HD dataset should include these data. If you want to test on your own data, you should do some preprocessing to get these data.
