### ISSUE TITLE
Traning code of diffusion model release

### ISSUE THREAD

**Issue by zmj1203** [bcmi/DCI-VTON-Virtual-Try-On#9]
Hi~ Thanks for your good work! I am quite interesting in it!
I noticed that you have uploaded lots of codes except the training part of diffusion model.
Do you plan to release the training code of diffusion model? if yes, when? Thank you!

**Comment by Limbor** [comment]
Hi @zmj1203 thanks for your interest of our work! We intend to release the training code of diffusion model in mid Sep.
